# Generated by Django 5.0.7 on 2024-09-28 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField(verbose_name='Date de début')),
                ('dateEnd', models.DateField(verbose_name='Date de fin')),
                ('displayNumber', models.IntegerField(blank=True, unique=True, verbose_name='Numéro de la semaine')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CM2', 'CM2'), ('SIXIEME', 'Sixieme')], default='CM2', max_length=16, verbose_name='Niveau scolaire')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la classe')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numericScore', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Score')),
                ('nullScoresPercentage', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Pourcentage de scores nuls')),
                ('mathadorsPercentage', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Pourcentage de Mathadors')),
                ('schoolClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculusModule.schoolclass', verbose_name='Classe')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculusModule.week', verbose_name='Semaine')),
            ],
            options={
                'unique_together': {('schoolClass', 'week')},
            },
        ),
    ]
